ALTER TABLE cards
ADD COLUMN IF NOT EXISTS price_usd NUMERIC,
ADD COLUMN IF NOT EXISTS price_last_updated TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS number TEXT GENERATED ALWAYS AS (card_number) STORED;

ALTER TABLE collections
ADD COLUMN IF NOT EXISTS price_usd NUMERIC,
ADD COLUMN IF NOT EXISTS price_last_updated TIMESTAMPTZ;
